version: "3.3"

services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=bd
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
